
from __future__ import annotations

ENGINE_SHARED_HEADER = r'''# Generated by stage3/agent. Do not edit by hand during evaluation.
from __future__ import annotations

import math
import os
from pathlib import Path

import torch
import torch.nn.functional as F


def _resolve_device(device: str) -> str:
    if device == "auto":
        return "cuda" if torch.cuda.is_available() else "cpu"
    if device.startswith("cuda") and not torch.cuda.is_available():
        return "cpu"
    return device


def _select_dtype(config: dict, device: str):
    if not str(device).startswith("cuda"):
        return torch.float32
    dtype = str(config.get("torch_dtype", "float16")).lower()
    if dtype in ("bfloat16", "bf16"):
        return torch.bfloat16
    return torch.float16


def _torch_load(path: Path):
    try:
        return torch.load(path, map_location="cpu", weights_only=True)
    except TypeError:
        return torch.load(path, map_location="cpu")


def _find_weight_file(weight_dir: str | os.PathLike[str]) -> Path:
    root = Path(weight_dir)
    candidates = [
        root / "model.pt",
        root / "model_weights.pt",
        root / "pytorch_model.bin",
        root / "weights.pt",
    ]
    candidates.extend(sorted(root.glob("*.pt")))
    for candidate in candidates:
        if candidate.exists():
            return candidate
    raise FileNotFoundError(f"no supported weight file found in {root}")


def _load_weights(weight_dir: str, device: str, dtype) -> dict[str, torch.Tensor]:
    state = _torch_load(_find_weight_file(weight_dir))
    if isinstance(state, dict):
        for key in ("state_dict", "model", "weights"):
            nested = state.get(key)
            if isinstance(nested, dict):
                state = nested
                break
    if not isinstance(state, dict):
        raise TypeError("weight file did not contain a state dict")
    return {name: tensor.to(device=device, dtype=dtype) for name, tensor in state.items()}


def _rmsnorm(x: torch.Tensor, weight: torch.Tensor, eps: float) -> torch.Tensor:
    x_float = x.float()
    variance = x_float.pow(2).mean(dim=-1, keepdim=True)
    x_norm = x_float * torch.rsqrt(variance + eps)
    return x_norm.to(x.dtype) * weight


def _apply_rope(q: torch.Tensor, k: torch.Tensor, positions: torch.Tensor, theta: float):
    dim = q.shape[-1]
    inv_freq = 1.0 / (theta ** (torch.arange(0, dim, 2, device=q.device, dtype=torch.float32) / dim))
    freqs = torch.outer(positions.to(torch.float32), inv_freq)
    cos = freqs.cos().to(q.dtype)[None, None, :, :]
    sin = freqs.sin().to(q.dtype)[None, None, :, :]

    def rotate(x: torch.Tensor) -> torch.Tensor:
        x_even = x[..., 0::2]
        x_odd = x[..., 1::2]
        x_rotated = torch.stack((x_even * cos - x_odd * sin, x_even * sin + x_odd * cos), dim=-1)
        return x_rotated.flatten(-2)

    return rotate(q), rotate(k)


def _repeat_kv(x: torch.Tensor, num_heads: int, num_kv_heads: int) -> torch.Tensor:
    if num_kv_heads == num_heads:
        return x
    repeat = num_heads // num_kv_heads
    return x.repeat_interleave(repeat, dim=1)
'''


def render_safe_baseline() -> str:
    return ENGINE_SHARED_HEADER + r'''

class Engine:
    def __init__(self, model_config: dict, weight_dir: str, device: str = "cuda"):
        self.config = model_config
        self.device = _resolve_device(device)
        self.dtype = _select_dtype(self.config, self.device)
        self.w = _load_weights(weight_dir, self.device, self.dtype)
        self.num_layers = int(self.config["num_hidden_layers"])
        self.num_heads = int(self.config["num_attention_heads"])
        self.num_kv_heads = int(self.config["num_key_value_heads"])
        self.hidden_size = int(self.config["hidden_size"])
        self.head_dim = int(self.config.get("head_dim", self.hidden_size // self.num_heads))
        self.eps = float(self.config.get("rms_norm_eps", 1e-5))
        self.rope_theta = float(self.config.get("rope_theta", 10000.0))
        self.requests: dict[int, torch.Tensor] = {}
        if self.num_heads % self.num_kv_heads != 0:
            raise ValueError("num_attention_heads must be divisible by num_key_value_heads")

    def prefill(self, request_ids, input_ids):
        outputs = []
        with torch.inference_mode():
            for rid, ids in zip(request_ids, input_ids):
                rid = int(rid)
                ids = ids.to(device=self.device, dtype=torch.long).flatten()
                self.requests[rid] = ids.clone()
                outputs.append(self._forward(ids.unsqueeze(0))[0, -1, :])
        return torch.stack(outputs, dim=0)

    def decode(self, request_ids, token_ids):
        token_ids = token_ids.to(device=self.device, dtype=torch.long).flatten()
        outputs = []
        with torch.inference_mode():
            for rid, tok in zip(request_ids, token_ids):
                rid = int(rid)
                if rid not in self.requests:
                    raise KeyError(f"decode called for unknown request id {rid}")
                self.requests[rid] = torch.cat([self.requests[rid], tok.reshape(1)])
                outputs.append(self._forward(self.requests[rid].unsqueeze(0))[0, -1, :])
        return torch.stack(outputs, dim=0)

    def remove(self, request_ids):
        for rid in request_ids:
            self.requests.pop(int(rid), None)

    def _forward(self, input_ids: torch.Tensor) -> torch.Tensor:
        x = self.w["embed_tokens.weight"][input_ids]
        batch, seqlen, _ = x.shape
        mask = torch.triu(
            torch.full((seqlen, seqlen), float("-inf"), device=self.device, dtype=torch.float32),
            diagonal=1,
        )[None, None, :, :]
        for layer_idx in range(self.num_layers):
            prefix = f"layers.{layer_idx}"
            residual = x
            x_norm = _rmsnorm(x, self.w[f"{prefix}.input_layernorm.weight"], self.eps)
            q = F.linear(x_norm, self.w[f"{prefix}.self_attn.q_proj.weight"])
            k = F.linear(x_norm, self.w[f"{prefix}.self_attn.k_proj.weight"])
            v = F.linear(x_norm, self.w[f"{prefix}.self_attn.v_proj.weight"])
            q = q.view(batch, seqlen, self.num_heads, self.head_dim).transpose(1, 2)
            k = k.view(batch, seqlen, self.num_kv_heads, self.head_dim).transpose(1, 2)
            v = v.view(batch, seqlen, self.num_kv_heads, self.head_dim).transpose(1, 2)
            positions = torch.arange(seqlen, device=self.device, dtype=torch.float32)
            q, k = _apply_rope(q, k, positions, self.rope_theta)
            attn_k = _repeat_kv(k, self.num_heads, self.num_kv_heads)
            attn_v = _repeat_kv(v, self.num_heads, self.num_kv_heads)
            attn = torch.matmul(q.float(), attn_k.float().transpose(-1, -2)) / math.sqrt(self.head_dim)
            attn = torch.softmax(attn + mask, dim=-1).to(x.dtype)
            y = torch.matmul(attn, attn_v)
            y = y.transpose(1, 2).contiguous().view(batch, seqlen, self.hidden_size)
            x = residual + F.linear(y, self.w[f"{prefix}.self_attn.o_proj.weight"])
            residual = x
            x_norm = _rmsnorm(x, self.w[f"{prefix}.post_attention_layernorm.weight"], self.eps)
            gate = F.linear(x_norm, self.w[f"{prefix}.mlp.gate_proj.weight"])
            up = F.linear(x_norm, self.w[f"{prefix}.mlp.up_proj.weight"])
            x = residual + F.linear(F.silu(gate) * up, self.w[f"{prefix}.mlp.down_proj.weight"])
        x = _rmsnorm(x, self.w["norm.weight"], self.eps)
        return F.linear(x, self.w["lm_head.weight"])


def create_engine(model_config: dict, weight_dir: str, device: str = "cuda"):
    return Engine(model_config, weight_dir, device)
'''


def render_kv_cache(candidate_name: str, group_decode: bool, group_prefill: bool) -> str:
    flags = f"GROUP_DECODE = {group_decode!r}\nGROUP_PREFILL = {group_prefill!r}\nCANDIDATE_NAME = {candidate_name!r}\n"
    return ENGINE_SHARED_HEADER + "\n" + flags + r'''

class RequestState:
    __slots__ = ("length", "cache")

    def __init__(self, length: int, cache):
        self.length = int(length)
        self.cache = cache


class Engine:
    def __init__(self, model_config: dict, weight_dir: str, device: str = "cuda"):
        self.config = model_config
        self.device = _resolve_device(device)
        self.dtype = _select_dtype(self.config, self.device)
        self.w = _load_weights(weight_dir, self.device, self.dtype)
        self.num_layers = int(self.config["num_hidden_layers"])
        self.num_heads = int(self.config["num_attention_heads"])
        self.num_kv_heads = int(self.config["num_key_value_heads"])
        self.hidden_size = int(self.config["hidden_size"])
        self.head_dim = int(self.config.get("head_dim", self.hidden_size // self.num_heads))
        self.eps = float(self.config.get("rms_norm_eps", 1e-5))
        self.rope_theta = float(self.config.get("rope_theta", 10000.0))
        self.requests: dict[int, RequestState] = {}
        self._mask_cache: dict[tuple[int, int, int], torch.Tensor] = {}
        if self.num_heads % self.num_kv_heads != 0:
            raise ValueError("num_attention_heads must be divisible by num_key_value_heads")

    def prefill(self, request_ids, input_ids):
        with torch.inference_mode():
            outputs = [None] * len(request_ids)
            groups: dict[int, list[tuple[int, int, torch.Tensor]]] = {}
            for index, (rid, ids) in enumerate(zip(request_ids, input_ids)):
                ids = ids.to(device=self.device, dtype=torch.long).flatten()
                if ids.numel() == 0:
                    raise ValueError("prefill requires at least one token")
                key = int(ids.numel()) if GROUP_PREFILL else -index - 1
                groups.setdefault(key, []).append((index, int(rid), ids))
            for _key, items in groups.items():
                batch_ids = torch.stack([item[2] for item in items], dim=0)
                logits, caches = self._forward_batch(batch_ids, past_key_values=None, start_pos=0, return_cache=True)
                for batch_index, (original_index, rid, ids) in enumerate(items):
                    cache = []
                    for layer_k, layer_v in caches:
                        cache.append((layer_k[batch_index].contiguous(), layer_v[batch_index].contiguous()))
                    self.requests[rid] = RequestState(int(ids.numel()), cache)
                    outputs[original_index] = logits[batch_index, -1, :]
            return torch.stack(outputs, dim=0)

    def decode(self, request_ids, token_ids):
        token_ids = token_ids.to(device=self.device, dtype=torch.long).flatten()
        if token_ids.numel() != len(request_ids):
            raise ValueError("decode token_ids length must match request_ids")
        with torch.inference_mode():
            outputs = [None] * len(request_ids)
            groups: dict[int, list[tuple[int, int, torch.Tensor, RequestState]]] = {}
            for index, (rid, tok) in enumerate(zip(request_ids, token_ids)):
                rid = int(rid)
                state = self.requests.get(rid)
                if state is None:
                    raise KeyError(f"decode called for unknown request id {rid}")
                key = state.length if GROUP_DECODE else -index - 1
                groups.setdefault(key, []).append((index, rid, tok.reshape(1), state))
            for _key, items in groups.items():
                start = items[0][3].length
                batch_tokens = torch.stack([item[2] for item in items], dim=0)
                past = self._stack_past([item[3] for item in items])
                logits, caches = self._forward_batch(batch_tokens, past_key_values=past, start_pos=start, return_cache=True)
                for batch_index, (original_index, rid, _tok, _state) in enumerate(items):
                    cache = []
                    for layer_k, layer_v in caches:
                        cache.append((layer_k[batch_index].contiguous(), layer_v[batch_index].contiguous()))
                    self.requests[rid] = RequestState(start + 1, cache)
                    outputs[original_index] = logits[batch_index, -1, :]
            return torch.stack(outputs, dim=0)

    def remove(self, request_ids):
        for rid in request_ids:
            self.requests.pop(int(rid), None)

    def _stack_past(self, states: list[RequestState]):
        past = []
        for layer_idx in range(self.num_layers):
            keys = [state.cache[layer_idx][0] for state in states]
            vals = [state.cache[layer_idx][1] for state in states]
            past.append((torch.stack(keys, dim=0), torch.stack(vals, dim=0)))
        return past

    def _forward_batch(self, input_ids: torch.Tensor, past_key_values=None, start_pos: int = 0, return_cache: bool = True):
        x = self.w["embed_tokens.weight"][input_ids]
        batch, seqlen, _ = x.shape
        next_cache = []
        positions = torch.arange(start_pos, start_pos + seqlen, device=self.device, dtype=torch.float32)
        for layer_idx in range(self.num_layers):
            prefix = f"layers.{layer_idx}"
            residual = x
            x_norm = _rmsnorm(x, self.w[f"{prefix}.input_layernorm.weight"], self.eps)
            q = F.linear(x_norm, self.w[f"{prefix}.self_attn.q_proj.weight"])
            k = F.linear(x_norm, self.w[f"{prefix}.self_attn.k_proj.weight"])
            v = F.linear(x_norm, self.w[f"{prefix}.self_attn.v_proj.weight"])
            q = q.view(batch, seqlen, self.num_heads, self.head_dim).transpose(1, 2)
            k = k.view(batch, seqlen, self.num_kv_heads, self.head_dim).transpose(1, 2)
            v = v.view(batch, seqlen, self.num_kv_heads, self.head_dim).transpose(1, 2)
            q, k = _apply_rope(q, k, positions, self.rope_theta)
            if past_key_values is None:
                full_k = k
                full_v = v
                key_start = 0
            else:
                past_k, past_v = past_key_values[layer_idx]
                full_k = torch.cat([past_k, k], dim=2)
                full_v = torch.cat([past_v, v], dim=2)
                key_start = int(past_k.shape[2])
            next_cache.append((full_k, full_v))
            attn_k = _repeat_kv(full_k, self.num_heads, self.num_kv_heads)
            attn_v = _repeat_kv(full_v, self.num_heads, self.num_kv_heads)
            attn = torch.matmul(q.float(), attn_k.float().transpose(-1, -2)) / math.sqrt(self.head_dim)
            mask = self._causal_mask(seqlen, attn_k.shape[-2], key_start)
            if mask is not None:
                attn = attn + mask
            attn = torch.softmax(attn, dim=-1).to(x.dtype)
            y = torch.matmul(attn, attn_v)
            y = y.transpose(1, 2).contiguous().view(batch, seqlen, self.hidden_size)
            x = residual + F.linear(y, self.w[f"{prefix}.self_attn.o_proj.weight"])
            residual = x
            x_norm = _rmsnorm(x, self.w[f"{prefix}.post_attention_layernorm.weight"], self.eps)
            gate = F.linear(x_norm, self.w[f"{prefix}.mlp.gate_proj.weight"])
            up = F.linear(x_norm, self.w[f"{prefix}.mlp.up_proj.weight"])
            x = residual + F.linear(F.silu(gate) * up, self.w[f"{prefix}.mlp.down_proj.weight"])
        x = _rmsnorm(x, self.w["norm.weight"], self.eps)
        logits = F.linear(x, self.w["lm_head.weight"])
        return logits, next_cache if return_cache else None

    def _causal_mask(self, query_len: int, key_len: int, key_start: int):
        if query_len == 1 and key_len == key_start + 1:
            return None
        cache_key = (query_len, key_len, key_start)
        mask = self._mask_cache.get(cache_key)
        if mask is None:
            query_positions = torch.arange(key_start, key_start + query_len, device=self.device)
            key_positions = torch.arange(0, key_len, device=self.device)
            blocked = key_positions[None, :] > query_positions[:, None]
            mask = torch.zeros((query_len, key_len), device=self.device, dtype=torch.float32)
            mask = mask.masked_fill(blocked, float("-inf"))[None, None, :, :]
            self._mask_cache[cache_key] = mask
        return mask


def create_engine(model_config: dict, weight_dir: str, device: str = "cuda"):
    return Engine(model_config, weight_dir, device)
'''
